### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#105]
Within the profile page for faculty <https://metadata.libraries.psu.edu/profile/bio>  to upload there should be a contact form or at the very least an email link: 
L-FAMS@lists.psu.edu for help

**Comment by EricDurante** [comment]
I added a "Support" link to the upper-right navigation in the profile management interface. It's just an email link for now. If a separate page with a contact form would be better, then we'll just need to discuss a few details about how that form should behave.
