### ISSUE TITLE
Automatically run the Open Access Button import on a regular schedule

### ISSUE THREAD

**Issue by EricDurante** [psu-stewardship/researcher-metadata#122]
This probably doesn't need to be done any more frequently than the import from Pure. We potentially could get new publication metadata from Activity Insight every day, but most of that metadata doesn't reliably contain valid DOIs which are our basis for querying Open Access Button. Pure imports currently happen much less frequently, but their publication metadata does reliably contain valid DOIs. Once we have Pure imports automated to the point where they're occurring on a scheduled basis, we should do the same with the OA Button import and ensure that it runs after each Pure import.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Yeah, the Pure import runs Saturday mornings, and the OA Button import runs Sunday mornings.  I closed the issue.
