### ISSUE TITLE
Distinguish between sources of open access urls

### ISSUE THREAD

**Issue by EricDurante** [psu-stewardship/researcher-metadata#131]
As we roll out reminder emails about the PSU open access policy, we'd like to be able to have some gauge of how effective they are. Specifically, we'd like to know how many publications in RMD have become (or been discovered as) open access as a result of faculty users either providing an existing open access URL or depositing an open access copy of their work into Scholarsphere as opposed to RMD automatically discovering open access work via Open Access Button.

Currently, when a faculty user submits an open access URL for a publication, that value gets stored in a different field than that in which a URL acquired from Open Access Button would be stored, so that helps us to distinguish between some open access URLs that we've obtained automatically and some which we've obtained from faculty. The problem that we have now is that whenever an RMD admin adds an open access URL for a publication that a faculty member has just deposited into Scholarsphere, that Scholarsphere URL gets stored in the same field that is used for URLs that we obtain automatically from Open Access Button. This makes it difficult to determine where exactly some of the open access URLs for publications in RMD came from.

The most obvious solution to this problem would be to store the Scholarsphere URLs that are entered by RMD admins in the same field where faculty-submitted open access URLs are stored instead of in the field where URLs from Open Access Button are stored. This would separate all of the URLs that we got automatically from all of the URLs that were provided by humans.

This obvious approach might not be the best, though, especially considering that we want to allow faculty users to be able to edit open access URLs that they have submitted themselves (https://github.com/psu-stewardship/researcher-metadata/issues/124). There are other considerations with regard to this editing ability that could affect how we solve this problem. In particular, if a publication has multiple authors, do we want to allow each author to submit their own open access URL for the publication that they can edit later? Or do we only want to store one URL for the publication and let any of the authors edit that same URL?

**Comment by DanCoughlin** [comment]
My initial reaction is, let's wait for it to be a problem before programming the complexity around something that may not be a problem. I think if a faculty member edits a url and we indicate "this will update the URL for the publication for all your co-authors as well" then they should know and be responsible. Thoughts?

**Comment by EricDurante** [comment]
That sounds fine to me, @DanCoughlin

Given that answer, I think the solution to this issue is going to be to add another field to publications just for storing Scholarsphere open access URLs (that are entered manually by RMD admins now and hopefully automatically by Scholarsphere itself someday). We wouldn't want to store those Scholarsphere URLs in the same field that faculty users can edit, and we also don't want to store it in the same field where the URLs from Open Access Button go (for the reasons explained above).

I don't think that'll be a huge deal at all. Adding the field and updating the Admin interface will be easy. Then tweaking the logic for the "preferred" open access URL should likewise be easy. I'd imagine that if we had a Scholarsphere URL, then that would be "preferred", and we'd want to provide it above all else, then a URL from OA button would come next, and finally a URL provided directly by an author. There may be a little bit of other logic to change in the open access workflow for faculty, but none of it is going to be tricky.

Just a note to self:
We'll also have to change how we're querying for open access publications in RMD (i.e. to generate the open access stats).

**Comment by EricDurante** [comment]
This has been completed.
