### ISSUE TITLE
Open Access Import

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#134]
This isn't a feature, just a holder for a TODO -- need to run OA Button import once we have everything in place for all potentially missing DOIs

dependent #133 Update missing DOIs

**Comment by EricDurante** [comment]
Also done 🙂

**Comment by DanCoughlin** [comment]
This was done post - missing DOIs presumably. Was it run after we sent the email to libraries?

**Comment by EricDurante** [comment]
@DanCoughlin 
Yes and yes.

We were only missing about 1600 DOIs, so chances are that it wouldn't have affected the libraries email in any way.
