### ISSUE TITLE
Modify AI publication importing to only import "direct" authorships

### ISSUE THREAD

**Issue by EricDurante** [psu-stewardship/researcher-metadata#138]
This is discussed in this basecamp thread starting at Jan 28:  https://3.basecamp.com/4206247/buckets/15288919/messages/3400105791#__recording_3424568680

This seems like it should "work" in theory to help avoid importing the incorrect authorships that are a problem in Activity Insight, but we still need to think through how well it would actually work in practice given the source data in AI and our process for merging duplicate data in RMD.

**Comment by DanCoughlin** [comment]
We will not be able to fix existing authorships where people have mistaken been identified as authors for papers they are not authors on; however, going forward we will only take AI publications that are associated with the user we are pulling information from. 

Example, If Jane puts Joe on a paper in AI, but Joe doesn't enter the paper in AI we have been previously been pulling in both Jane and Joe on the paper. Moving forward we will only pull in Jane as an author on the paper. If Joe would like to have the paper pulled in then he will have to enter the paper into AI as well.

**Comment by EricDurante** [comment]
We decided that we need to try to do three separate but related things in order to completely handle the incorrect authorship information that is coming out of Activity Insight. Those three things are as follows:

**First Item:**

We need to modify the code that imports metadata from Activity Insight and creates both `Authorship` and `Contributor` records in RMD. As it stands, we import metadata by person from AI and we iterate over all of the publications that the person has recorded in AI and then over all of the authors that they have recorded for each publication (including themselves) to create `Authorship`s and `Contributor`s. The problem is that in come cases, some of the authors that they listed in AI may be incorrect. What we need to do instead is to create only one `Authorship` record for each publication that we import from AI - this record should link the publication to the person who recorded the data in AI. We'll still need to look at the authorship data from AI to determine this author's position in the list, but we won't use the rest of the metadata to create `Authorship` records for any other Penn State authors that are listed because they may be incorrect. We'll still create the list of `Contributors` by iterating over the AI authorship metadata and saving each record, but we need to apply a new rule:  if an author isn't a user in AI, then we need to convert their first name to just a first initial (because the full first name could be incorrect, but the first initial shouldn't be).


**Second Item:**

This item is useful on its own, but it will be particularly useful with respect to this problem of correcting AI data. We need to modify the process of merging (duplicate) publication records so that it combines all of the `Contributor`s that are associated with each publication that's being merged, removes any duplicates from that set, and associates the resulting set with the resulting publication. The criterion for identifying duplicate `Contributor`s is a match on both first initial and last name.


**Third Item:**

After the first item has been completed, we need to deal with incorrect `Authorship`s and `Contributor`s that have already been imported into RMD from AI. The easiest way to do this will be to delete all of the `Authorship` records that are associated with every publication that in turn is associated with an Activity Insight import record and does not contain any data that has been provided by an RMD faculty user. After deleting this data (which will include both correct and incorrect authorship records), we'll need to do a special reimport of just `Authorship` and `Contributor` records from AI using the new logic described in the first item. We'll need to import this data even for publication records that have been modified by an RMD admin user, and we'll still need to check for existing `Authorship` records so as to not create any duplicates.

**Comment by EricDurante** [comment]
I'm finished with the first item in development, and I think it's ready to go into production.

I took a closer look at the second item by examining some real metadata to see how it would work. I _immediately_ found an edge case where the proposed solution would not work correctly. In this case, it was a Penn State author who had changed their last name (it looks like they appended a second surname). They entered some publication metadata where they listed themselves as an author, but their new last name was listed even though they were using their old last name whenever the article was published. Another Penn State Author listed the same publication, but correctly listed the first author's old last name. In this case, if we merged contributors as described above, we'd have a list that contained the same person twice - once with the original last name and once with the new last name.

This points me in the direction of doing two additional things for Item #2 one of which is a bit of effort, and the other of which is very minor but important in my opinion: 

1. We should create a link between `User` records and `Contributor` records where ever it's possible to do that. This would solve the issue with the edge case above because it would allow us to first compare `Contributor` records by `User`, and then only compare by first initial and last name if there is no `User` match. This also reveals that this is a potentially important/useful piece of information that we could have but currently don't. If we had this information, then for any given user we'd be able to ask the question, "What are all of the names by which this person has ever listed themselves as an author on a publication?". This leads me to:
2. We should rename the `Contributor` model. The current name is terrible, and it creates confusion because it doesn't meaningfully describe the data that it holds. At worst, it's actually misleading. I think it should be changed to something like `ContributorName`. `AuthorName` is tempting, but for some kinds of publications it may sometimes be inaccurate, and the broader "contributor" would be more appropriate. With this change, especially if the records are associated with users, it would make a lot more sense to say, "What are all of this user's contributor names?" vs. "What are all of this user's contributors". This little change will make it a lot easier to talk and think about these concepts.

I could definitely see where having a list of all of the names by which a user has been known could help us to correctly attribute works to that person from other data sources where the identity of people is ambiguous.

**Comment by EricDurante** [comment]
Ugh, scratch the first thing that I listed in that last post. The `User`/`ContributorName` connection might still be useful someday, but it's not going to help with merging contributor names. I was forgetting that we wouldn't be able to make that connection reliably in most cases from the metadata in Activity Insight.

I'm a lot less optimistic now that there's a reliable way to automate the merging of contributor names. This might just have to remain a manual process if we want maximum correctness. The good news is that Pure seems to have contributor name metadata that is generally both complete and correct, so the automatic merges involving Pure publications should result in good data in RMD, and so will any manual merge where a Pure publication is chosen to keep. For merges involving only Activity Insight publications, RMD admins will still need to compare the lists of contributor names and fix any mistakes/omissions on the merge target before merging.

**Comment by EricDurante** [comment]
The upshot of not being able to reliably merge contributor name data automatically is that we probably won't want to delete existing contributor names for publications that have been merged because we won't be able to automatically merge the names upon reimporting them. We'd just be trading one set of mistakes for another. Unfortunately I can't really see a better course of action than to just live with any incorrect contributor names that we already have until someone eventually stumbles upon them and asks an RMD admin to do a manual correction.

**Comment by EricDurante** [comment]
I think I have the process for item #3 worked out (for authorship records only). I'm running it in development currently to see what the results look like.
