### ISSUE TITLE
Update Email Text

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#140]
Attaching word doc with minor changes:     Update email text to include add URL for OA version option. (Current text is "follow the instructions to provide your accepted manuscript or obtain a waiver of the policy.") 
[Nudge email text_20210208.docx](https://github.com/psu-stewardship/researcher-metadata/files/5945798/Nudge.email.text_20210208.docx)

**Comment by EricDurante** [comment]
I only noticed one other change in the document apart from the one mentioned above, and I've made both of those changes.
