### ISSUE TITLE
Space issue in email text

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#141]
In some hyperlinks on email text no space appears before the hyperlink, may need a deliberate `&nbsp;` ? Attaching a screenshot that shows the issue. 

<img width="873" alt="Screen Shot 2021-02-08 at 12 22 45 PM" src="https://user-images.githubusercontent.com/398837/107263117-623ab380-6a0f-11eb-9594-26ea928fcc14.png">

**Comment by EricDurante** [comment]
Hmm. That's odd. This email renders fine without this spacing issue both in my browser and in several different email clients that I've tried. The HTML itself also appears to be correct. So far I'm unable to reproduce the problem. Has anybody else noticed this issue? Do you happen to know what kind of email client Victoria is using?
