### ISSUE TITLE
Publications from AI Current Status

### ISSUE THREAD

**Issue by nmg110** [psu-stewardship/researcher-metadata#155]
When pulling all publications from AI, we should think of only pulling in those with the Current Status of In Press or Published. Accepted, Submitted or Revising to Resubmit are works that are still in the "thought process" and can still be declined from the publisher.

**Comment by EricDurante** [comment]
Just a note here - we do currently check the status of publications coming in from AI, and we only import publications with a status of 'Published'. That could be expanded to include publications with a status of 'In Press'.
