### ISSUE TITLE
Content Changes for RMD-ScholarSphere integration

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#168]
1. The integration page where you upload a PDF to ScholarSphere likely needs better text 
- Typo: “If an open access version of your work has been pulished” 

2. Any suggestions on the labels for the form
- Description field can we say: "Include the work abstract if available. Otherwise, provide a brief summary."
- Link to help text for license selection "For help determining License and Embargo, see this FAQ" https://psu.libanswers.com/faq/279046
- Move the license field below DOI so that it's adjacent to Embargo
- Date of Publication should allow for selection of a future year (2 calendar years beyond current)
- Change "Publisher" to "Journal Name" and prepopulate with Journal, this will map to Publisher field in SS, but it's something we need to fix on SS side

3. Email from ScholarSphere when upload
- Successful `You recently submitted an open access version of your publication, Ana's Test Article, for deposit in ScholarSphere in order to comply with Penn State Policy AC02: Open Access to Scholarly Articles. This message is to let you know that the deposit of your publication was successful, and you can now view the open access version of your publication here: [LINK]` 
-  Unsuccessful `You recently submitted an open access version of your publication, Ana's Test Article, for deposit in ScholarSphere in order to comply with Penn State Policy AC02: Open Access to Scholarly Articles. There was an issue uploading the publication. Staff are working on this and we will follow up with you.`

**Comment by EricDurante** [comment]
@DanCoughlin All of these changes have been deployed to https://stage.metadata.libraries.psu.edu. Please let me know if you have any further feedback or additional changes.

When we add the field for "publisher statement" to the form, I imagine that we might need a little bit of instruction to accompany that as well.
