### ISSUE TITLE
Admin ScholarSphere Upload Integration

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#183]
We need a way for admins or assigned users to be able to upload PDFs to ScholarSphere on behalf of users. For example, a researcher responds to the nudge email by sending an attachment to Ana. It would be simplest if Ana could then upload the file on their behalf to ScholarSphere and have RMD update as the integration does for users.

**Comment by awead** [comment]
We've had the concept of "on behalf of" in the past, and it's always been a little confusing. Currently in Scholarsphere, we have depositors as well as proxies. In the above scenario, there are two options:

1. Ana is the de facto depositor, the person she's uploading for, or on behalf of, is the creator.
2. Ana is the depositor, the person she's uploading for, or on behalf of, is the both depositor and creator.

Option 1 is the simplest. Option 2 has the added problem that the depositor _must_ be an active Penn State user. So if that person is no longer at Penn State, it would have to be option 1.

**Comment by anaelizabethenriquez** [comment]
Duplicates #194
