### ISSUE TITLE
Add 'accessible' field to publication records that pull from AI.

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#189]
@nmg110 can provide additional details for this, but pretty sure she wants a field that pulls in a status for AI records.

**Comment by ajkiessl** [comment]
If an Activity Insight record has a submitted post-print, and Nicole or someone on Nicole's team has started to review it, they will update the 'ACCESSIBLE' field to 'In Progress'.  This could be helpful in determining who should receive emails.  We should pull this into RMD.  The field in AI is a dropdown with these potential values:

- In Progress
- Deposited to ScholarSphere
- Already Openly Available
- Cannot Deposit
- File provided was not a post-print

**Comment by ajkiessl** [comment]
Should be able to filter on this in rails admin.
