### ISSUE TITLE
Explore Open Access Button and Unpaywall

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#199]
We've found OAB API to be volatile at times, look to see if Unpaywall 
1- has the same attributes we are getting from OAB
2- are we able to query it at the same rates with equal or greater success

## What Done Looks Like

* report on the Unpaywall API comparing attributes between OAB (Open Access Button)
* answer questions (or give a vague idea) about query rates' of success: Do we have a better, lesser, or equal chance of determining access via UnPaywall or OAB

## Conclusion

We will use both OAB and Unpaywall until we decide there is a reason not to.

**Comment by EricDurante** [comment]
Note:  Both OAB and Unpaywall ask users to voluntarily rate limit themselves when using their APIs. I think this is enforced entirely via the honor system, but we should be good citizens nevertheless. For OAB I believe it's no more than 1 request per second, and for Unpaywall it looks like it's no more than 100,000 requests per day. That means that we can't query either API for all of our publications (that have a DOI) in a single day. In both cases, it would have to be spread out over at least two days.

**Comment by EricDurante** [comment]
Agreed!

**Comment by EricDurante** [comment]
How strange. For being the Director / Co-Founder, Joe sounds pretty "meh" on OAB at this point..

Nevertheless, I like the name change. "Open Access Button" was a mouthful, and kind of a confusing name.

Thanks for the update, Ana.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I see this was moved into Complete (Deployed to Production) but hasn't been closed.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez This can be closed.
