### ISSUE TITLE
Import open access metadata from Unpaywall

### ISSUE THREAD

**Issue by EricDurante** [psu-stewardship/researcher-metadata#257]
Using the updated data model (https://github.com/psu-stewardship/researcher-metadata/issues/192) we need to be able to automatically query Unpaywall's [API](https://unpaywall.org/products/api) for each of our publications that has a DOI, and store any open access [metadata](https://unpaywall.org/data-format) that is returned. If any metadata exists, it should create/update an `OpenAccessLocation` record that is associated with the publication, and it should also update the `Publication`'s `open_access_status` field.

This import needs to run in such a way that it does not exceed Unpaywall's rate limit of 100,000 requests/day. Like the Open Access Button import, this import should be scheduled to run automatically once per week, and it should continue and log issues after encountering any unexpected errors.

**Comment by DanCoughlin** [comment]
This is from a script I wrote earlier this year to get the OA Status from unpaywall
```
if !doi.empty?
            puts "#{doi}"
            doi = doi.sub "https://", ""
            url = "https://api.unpaywall.org/v2/#{doi}?email=dmc186@psu.edu"
            begin
                response = HTTParty.get(url)
                res = response.parsed_response
                puts res['oa_status']
                wr_sheet.row(row_index).insert OA_STATUS_COLUMN, res['oa_status']
            rescue URI::InvalidURIError
                puts "Invalid doi"
                wr_sheet.row(row_index).insert OA_STATUS_COLUMN, "Invalid DOI"
            rescue Net::OpenTimeout
                wr_sheet.row(row_index).insert OA_STATUS_COLUMN, "timeout"
            end

        end

```

**Comment by anaelizabethenriquez** [comment]
I'm not sure, @nicktiberi. I would certainly defer to any conventions you all would normally follow here. One option would be to use openaccess@psu.edu. This is the general contact address for OA stuff. Mostly I answer those emails, but others have access to the email queue in case I'm not available. I'm not aware of an equivalent address for the overall RMD project, but since this Unpaywall piece is OA-related, I think it's OK.
