### ISSUE TITLE
Allow an RMD user to assign another RMD user as their delegate

### ISSUE THREAD

**Issue by awead** [psu-stewardship/researcher-metadata#269]
RMD users may select one or more "delegates" who will allowed to perform actions on behalf of the other user.

## WDDLL

* existing user enters webaccess id of delegate
* UI elements for adding, and removing delegates
* users can see delegates they have appointed and see if they are a delegate for someone else 
* delegate is added as an RMD user (unless they already exist)
* Display the name of the delegate the user has added after submitting

### Active vs Confirmed

A `DeputyAssignment` has two flags on it, `confirmed_at` and `is_active`, which interact as follows:

`is_active` is essentially the "does this item exist" flag. Deputy assignments are never deleted, the act of removing a deputy assignment is to flip the `is_active` flag to false. At the controller code level, all interaction with the `DeputyAssignment` model should be done with `is_active: true`. 

`confirmed_at` is a timestamp indicating whether the deputy has accepted the deputy assignment. 

When a primary invites a deputy, but that deputy has not yet confirmed, then the `DeputyAssignment` will look like `is_active: true, confirmed_at: nil`.

### Adding a delegate

A user types an access id into a text field. Assuming the access id is valid, there are several scenarios:

1. **Access ID is not known to RMD:** create a User record, create a DeputyAssignment(is_active: true, confirmed_at: nil)
1. **RMD has a User record for that access id, but no DeputyAssignment for that pair:** create a DeputyAssignment(is_active: true, confirmed_at: nil)
1. **RMD has a User record for that access id, and there is an _inactive_ DeputyAssignment for the pair:** create a new DeputyAssignment(is_active: true, confirmed_at: nil)
1. **RMD has a User record for that access id, and there is already and active DeputyAssignment:** task failed successfully

Therefore the algorithm for adding a new delegate should be:
1. Look for an existing User with that access id
    1. If none exists, query PSU identity, and create a User if that's successful
1. Look for an existing _active_ DeputyAssignment between the current_user and the User from step 1
    1. if one exists that is _active_ then abort. There's nothing to do. 
1. Create a new DeputyAssignment with `is_active: true, confirmed_at: nil`.

### Removing a delegate

If a DeputyAssignment is active and unconfirmed, then it can be deleted. 

Once a DeputyAssignment is confirmed, it can never be deleted, it can only be deactivated.

## Examples

![Screen Shot 2021-10-14 at 2 10 10 PM](https://user-images.githubusercontent.com/312085/137372759-1b33d7d5-f042-4bab-9a19-32859362926f.png)

**Comment by ajkiessl** [comment]
If a delegate has never been confirmed, they can be deleted.
