### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#29]
The system should sent out confirmation emails and the waiver system for user taken actions.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-28

**Comment by EricDurante** [comment]
@DanCoughlin 

This is done and deployed to the staging site. You should be able to try it by submitting a waiver here:  https://stage.metadata.libraries.psu.edu/profile/publications/open_access_waivers/new

Please let me know if you'd like to change anything about the email message, or let me know if everything looks good, and then I'll get this deployed to production.

**Comment by DanCoughlin** [comment]
@EricDurante  - here is preferred text for confirmation. Thanks!
To: [email address provided in form]
Subject: PSU Open Access Policy Waiver for Requested Article

Dear [First] [Last],

Pursuant to Penn State Policy AC02: Open Access to Scholarly Articles, this communication serves to notify you that your request for a waiver of the Open Access license for [Article Title] in [Journal Title] has been granted. This waiver may not be revoked by Penn State, and Penn State will have no license under the policy unless you choose to relinquish the waiver.

Independent of the waiver, we recommend that you deposit your article in the ScholarSphere repository. In cases where you receive a waiver of Policy AC02, the publisher's agreement may still provide sufficient rights to allow copies of your article to be made publicly available in ScholarSphere. The publisher may ask that certain conditions be met, some of which the repository can easily accommodate (for example, an embargo period during which the article will not be made publicly available).

If you have any questions about this waiver, Policy AC02, or depositing a copy of your article in ScholarSphere, please contact the Office of Scholarly Communications and Copyright.
 
Important note for sponsored research: Even though you are being granted a waiver of the application of Penn State Policy AC02: Open Access to Scholarly Articles to your article specified above, if that article is subject to public access or open access requirements from your funder, such as the NIH, NSF, and DOE Public Access Policies, your obligations under your grant cannot be waived. You must be sure to reserve rights sufficient to comply with your funder's policy when you enter into a publication agreement for the article.

Sincerely,

The Office of Scholarly Communications and Copyright
Penn State University Libraries

**Comment by DanCoughlin** [comment]
@EricDurante Can you update the email with the above changes 
I've added links, and the reply to address. Thanks!
