### ISSUE TITLE
Pull OA Files from Digital Measures 

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#30]
Add ability to get files that have been uploaded associated with a publication as an OA copy in DM.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-27

**Comment by anaelizabethenriquez** [comment]
@DanCoughlin Is this complete now that we are importing new ScholarSphere links regularly? Or did this mean something else?

**Comment by DanCoughlin** [comment]
@anaelizabethenriquez yup, it's complete. Closing now.
