### ISSUE TITLE
Open Access Email Workflow

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#31]
Penn State's open access policy, AC02, went into effect January 1, 2020, and it applies to all articles published after that date except those for which the authors have requested a waiver because they "entered into an incompatible licensing or assignment agreement before the adoption of this policy".

We want to actively reach out to authors to ask them to comply with the policy for any articles that they have published after the policy start date. Through the faculty profile management interface in the metadata database app, users already have the ability to either:
1. enter a URL to an existing open access copy on the web,
2. go to Scholarsphere to upload an open access copy, or
3. waive their open access obligations

for each of their publications in the metadata database with an unknown open access status.

What we would like to do is to send an email to remind faculty members who have articles that are subject to the policy to visit the metadata database site and do one of these things for each article.

Some things to consider:
- Emails should only be sent to users who have one or more affected articles for which we do not already know the open access status (i.e. we don't have an associated open access URL, pending Scholarsphere upload, or waiver for the article).
- The email content should list the titles of the affected articles, and it should contain a link for each article to that article's "open access management page" in the profile management interface in the metadata database app. It should also contain some instructions for what the user should do when they visit those pages.
- This email doesn't need to be triggered by a person (i.e. a metadata database admin). It can happen automatically on a regular schedule.
- We don't want to nag people, so we want to be sure that we don't send any given person too many emails - especially about the same articles. The overall timing of when the email sending will be triggered may be relatively infrequent (once every few months?). However, for each user we may want to keep track of the date on which the last reminder email was sent to them. We can use this information to make sure that we don't send an email to any given user too often even if the email sending is triggered more frequently.

Related #76 Email Text

**Comment by DanCoughlin** [comment]
@EricDurante If we've already emailed a person about a particular article, and now it's time to send emails again and that person has a new article but still hasn't done anything about the old article, do we remind them about both or just the new one? 

I think we remind them about both. It would be great, although maybe not necessary immediately, if we could segment the email "New Articles Awaiting Action" and "Previous Articles Awaiting Action"

**Comment by EricDurante** [comment]
@DanCoughlin 
Ok, that sounds good. It wouldn't be too difficult to separate the articles in that way. We can easily keep track of which articles a user has been notified about previously.

Overall how frequently would we want someone to receive one of these emails? This doesn't necessarily need to be the same interval on which we actually send email. For example, if we wanted to send emails somewhat frequently (like once per month or at any other arbitrary interval) to catch any new users that have been added to the database during that time, then we could go ahead and do that, and then each time that we send email, we could check the date when each user last received an email and _not_ send email to users who have already been notified recently.
