### ISSUE TITLE
Things to do before OA emailing

### ISSUE THREAD

**Issue by ajkiessl** [psu-stewardship/researcher-metadata#344]
Emailing will begin on Monday, Nov 15th.

Things to do before then (in no particular order):

- [x] Run OAB import
- [x] Match external waivers
- [x] Run Unpaywall import
- [x] Run PSU Identity import
- [x] Figure out how many emails will be sent for each organization
- [x] Run auto dedupe
- [x] Generate list of people to receive emails for Nicole
- [x] Run Unpaywall import on Monday for any non-checked publications

We should start with small batches of emails first.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Could we re-run the Unpaywall import, using the version of the task that only checks things that haven't been checked (that exists, right?), right before sending emails? I see about 200 items that have DOIs but no Unpaywall timestamp, presumably things imported this week. If we can avoid sending emails unnecessarily, that's really helpful.

**Comment by ajkiessl** [comment]
Yeah that exists and I can run it again on Monday (I'll actually try to test this out today).  It shouldn't take very long to complete.  However, a lot of the 200 publications that have DOIs, but no Unpaywall timestamp, are probably publications that encountered an error during import (there are 238 of them): 

https://metadata.libraries.psu.edu/admin/importer_error_log?model_name=importer_error_log&utf8=%E2%9C%93&f%5Boccurred_at%5D%5B31906%5D%5Bo%5D=between&f%5Boccurred_at%5D%5B31906%5D%5Bv%5D%5B%5D=&f%5Boccurred_at%5D%5B31906%5D%5Bv%5D%5B%5D=November%2009%2C%202021%2011%3A06&f%5Boccurred_at%5D%5B31906%5D%5Bv%5D%5B%5D=November%2012%2C%202021%2011%3A06&f%5Bimporter_type%5D%5B33643%5D%5Bo%5D=is&f%5Bimporter_type%5D%5B33643%5D%5Bv%5D=UnpaywallPublicationImporter&query=

I don't know if I'll be able to get a reliable patch out by Monday to fix these errors.  

The Open Access Button import will run on Sunday, though, and may be able to find some of these missing URLs.

**Comment by anaelizabethenriquez** [comment]
OK, thanks @ajkiessl . I realized I should have put on one more filter, for publication dates on or after July 1, 2020. (It's nice to get Unpaywall data for earlier publications but we don't include them in the emails). Doing this brings the number down to three publications. I'll take a quick look at them manually. If you could still run it on Monday for things that get imported over the weekend, that would be great.

**Comment by anaelizabethenriquez** [comment]
> We should start with small batches of emails first.

Doing small batches on Monday, to start, sounds excellent. Please let me know how I can help with selecting organizations and timing.
