### ISSUE TITLE
Adding authorship in admin interface

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#365]
Is it supposed to be possible for an admin to add an authorship to a publication in the admin interface? I don't think it currently is.

Here's what I see:

- Go to a publication and select the "Edit" pane.
- Next to "Authorships," there is a two-part button. Clicking the arrow icon unfurls information about the existing authorship(s). The other part of the button says "+ Add new Authorship."
- Clicking "+ Add new Authorship" shows a new Authorship with three empty fields: 
  - User (required) -- This field is not editable.
  - Author number (required) -- This field is not editable.
  - Orcid resource identifier (optional) -- This field appears to be editable.

@EricDurante mentioned this might be possible only from one direction, so I wonder if there's another place I should be trying to do this.

**Comment by EricDurante** [comment]
@anaelizabethenriquez Oh yes - I see what you're saying now. That's the result of a bit of a bug in the rails_admin engine. It should allow us to specify different behavior for creating an authorship vs. editing an existing authorship in the context of editing a publication, but it doesn't actually work that way. If you specify behavior (i.e. non-editable fields) for either creating or editing, then it applies to both actions in that context.

I think the only ways around this would be to loosen the restrictions on editing existing authorship records or to allow admins to create authorships outside of the context of editing a publication or a user. The former would allow admins to do some things that they shouldn't need to do, but it's probably not a big deal. The latter would keep the restrictions in place, but it might be slightly less convenient for the admin user than the alternative.
