### ISSUE TITLE
Proxy Emails: Proxy Revocation and End Proxy Status

### ISSUE THREAD

**Issue by nicktiberi** [psu-stewardship/researcher-metadata#367]
In addition to our current slate of proxy-related emails, we should also send emails in the following two scenarios: 

- send an email to the primary user if the proxy decides to end their proxy status
- send an email to the proxy if the primary user revokes the the proxy user's proxy status

**Comment by nicktiberi** [comment]
@anaelizabethenriquez - please let me know what you would like for the content of these emails and I can wire them up. Thanks! 🙂

**Comment by anaelizabethenriquez** [comment]
@nicktiberi here's the text. If you haven't already, can you either send these (and the other proxy-related emails) as openaccess@psu.edu or make it the Reply-To address?

PSU Researcher Metadata Database - Proxy Status Ended

Dear <primary user name>,

<deputy name> <deputy Access ID> has ended their status as a proxy acting on your behalf in the Researcher Metadata Database. They can no longer act on your behalf. If this was a mistake, you can try adding them as a proxy again.

With questions, contact openaccess@psu.edu.

Sincerely,
The Researcher Metadata Database Team

PSU Researcher Metadata Database - Proxy Status Revoked

Dear <deputy name>,

<primary user name> <primary user Access ID> has revoked your status as a proxy acting on their behalf in the Researcher Metadata Database. You can no longer act on their behalf. If this was a mistake, they can add you as a proxy again.

With questions, contact openaccess@psu.edu.

Sincerely,
The Researcher Metadata Database Team
