### ISSUE TITLE
External waivers coming from RMD users who are authors on the publication

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#379]
I see a couple of external publication waivers that came in yesterday. Each is already matched with the appropriate publication. I'm deliberating not linking them so I can log this issue. (tagging @DanCoughlin so he won't match them either)

- https://metadata.libraries.psu.edu/admin/external_publication_waiver/72
- https://metadata.libraries.psu.edu/admin/external_publication_waiver/71

The unexpected thing about these waivers is that they come from users who have these publications in their profiles and received nudge emails about them. Are they just entering new waivers because they can't figure out how to do a regular internal waiver? Or is something malfunctioning?

**Comment by DanCoughlin** [comment]
I see this 👀  @anaelizabethenriquez and will not tag :-)

**Comment by ajkiessl** [comment]
@anaelizabethenriquez It looks like everything is working properly.  I forget what external sites link to the external waiver.  Perhaps these users' departments or someone they know who has used the external waiver form recommended that they use this to submit a waiver.  They may not know about the internal waiver form since the link to that form is at the bottom of the open access publication edit page.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl OK. Thanks for checking. I think you can close this. I'll go ahead and link up the publications.

I'm not aware of anyone linking directly to the external waiver form, but it's possible. In the things we put out, we use always use https://openaccess.psu.edu/waiver/. That redirects to a page that forces the user to authenticate and then sends them either to https://metadata.libraries.psu.edu/profile/publications/edit (if they have an RMD profile) or to the WordPress form (if they don't have an RMD profile). 

I suspect these two came to the external waiver form from the publications page ("If you need to waive open access obligations for a publication that is not in the list below, then please fill out this waiver form."). Looking at it, that's a little more prominent than clicking on the publication to waive (at which point the user has to scroll way down past the ScholarSphere form). Down the road, we may want to review the design of those two pages, from the user perspective.
