### ISSUE TITLE
Admin cannot "unbecome" user

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#399]
While testing in QA, I noticed that as an admin I cannot "unbecome" a user. I get the error message "Your account is not authorized to perform this action." I have been using this feature in production, where it is working fine.

Update: This is only a problem when I click on the "Unbecome this user" button. If I click "stop being [username]" in the header, it works fine.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez There was a bug causing this.  I'm working on a patch to fix it.
