### ISSUE TITLE
Import publisher data for publications from Pure

### ISSUE THREAD

**Issue by njnash** [psu-stewardship/researcher-metadata#41]
**Background:**
Activity Insight and Pure both have a means to provide information about the journals in which publications appear and about the publishers of those journals. Activity Insight provides both the "journal" and the "publisher" for a publication as simple strings, and if these are present, then we import and save them - also as simple strings - in the metadata database. However, that data is not always provided by Activity Insight, and when it is, it's often not consistent. Pure, on the other hand, represents both journals and publishers as separate records that are related to a publication. For the purposes of our Pure importing, we're currently finding the journal record that is associated with a publication that we're importing and recording it's name in the same string field in the metadata database that we use to store journal names from Activity Insight. We're not currently importing any publisher information from Pure at all.

**Use case:**
PSU library staff would like to be able to reliably query publications in the metadata database by publisher so that they can determine which publishers have published the largest number of research articles produced by Penn State researchers. This will inform them which publishers would give them the best return on investment of effort with regard to negotiating open access policies, etc.

**Implementation notes:**
At the very least, we can find the names of the publishers in Pure's publisher records that are associated with publications and import those names as strings - just like we're currently doing with journal names from Pure and both journal names and publisher names from Activity Insight. We may want to consider representing publishers as separate records in the metadata database in the same way that Pure does, though this might not be necessary or even terribly helpful just for the purposes of this story.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-18

**Comment by DanCoughlin** [comment]
Adding note from duplicate issue: We need to link the journals in the citations to publishers so that we can find out what publishers we put out the most content, then we can see who to look for licensing deals with

Also - If we could get publishers into the DB then we could see what journals we also have the most OA content from

**Comment by EricDurante** [comment]
Since I need to put work on this feature aside for now, I'm just leaving a note here to remind myself of the current status later. It's well-described in this commit message:  https://github.com/psu-stewardship/researcher-metadata/commit/cfc9fd00114751cb8fbedd0cb9bfa2ae4f037dd3
