### ISSUE TITLE
Profile page won't load

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#414]
I'm trying to load the profile page for rmn12 in order to use the admin proxy feature. 

I'm getting the following error:

> We're sorry, but something went wrong.
> 
> If you are the application owner check the logs for more information.
> 
I'm able to load other profile pages.

This may be related to #361 , which was resolved. The page for mgn1, mentioned in that issue, won't load either.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez I released a patch to production to fix this just now.  When I fixed this issue a couple weeks ago, I released the fix to production but never merged the code into our main branch of code.  So, the fixes were eventually overwritten.  Luckily, I still had the branch with the fixes locally, and it was easy to get merged into the main branch.  Our branching strategy was a little confusing for the last development cycle.  We'll use a better strategy moving forward which will prevent issues like this from happening again.
