### ISSUE TITLE
Upgrade Ruby to at least 2.7

### ISSUE THREAD

**Issue by ajkiessl** [psu-stewardship/researcher-metadata#443]
Ruby 2.6's EOL is March 31st 2022.

**Comment by EricDurante** [comment]
Hey @ajkiessl,
I can handle this upgrade. It falls under our "foundation service" agreement, and I might be the only person who's currently in a good position to actually get it done anyway. We'll schedule it for sometime in the next couple of weeks.

**Comment by ajkiessl** [comment]
Sounds good.  Thanks @EricDurante !

**Comment by EricDurante** [comment]
Ruby has been upgraded to version 2.7 on each of the application servers.

![Screen Shot 2022-03-09 at 6 53 57 PM](https://user-images.githubusercontent.com/881801/157559325-92378c30-2780-4265-9e70-f354f75c2420.png)

**Comment by ajkiessl** [comment]
Thanks @EricDurante .  I'm going to close this and open another ticket to upgrade to ruby 3.  2.7 is the last version of 2, and I figure upgrading to 3 will be pretty involved.  Just want to have a ticket out there so we remember to get to it before March 2023.

**Comment by EricDurante** [comment]
That's perfect - thanks, @ajkiessl. 

The only reason that I didn't try to push it further ahead now is that my time is a bit limited at the moment, and, like you said, I wasn't sure how difficult it would be. I think that most of our gems are fairly up-to-date now, which means that hopefully they all have support for Ruby 3. In that case, it might actually not be too bad. Our code probably doesn't care much whether it's running on Ruby 2 or 3.
