### ISSUE TITLE
Create templates, sample code, and instructions for using user profile JSON API

### ISSUE THREAD

**Issue by njnash** [psu-stewardship/researcher-metadata#56]
The Javascript and Handlebars template used by the updated profile demo site can serve as the basis for this. Then we'll just provide a few additional templates that have the content arranged in various different ways and some instructions for using them. We can host this content on a new public page on the Metadata Rails app.

Note:  The current profile demo site is using the beta version of the Metadata app. Any sample code that we provide should use the production version of the Metadata app.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-3

**Comment by EricDurante** [comment]
This was also done a long time ago.
