### ISSUE TITLE
Write Publications to ORCiD

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#59]
Create a link to ORCID that allows users to write their publications to ORCID works. First priority is likely writing our publications to ORCID works, then it would be great in no order to work on

1. Membership & Services
2. Education & Qualifications
3. Employment

There are others that would be valuable but not sure we store it here (i.e. Invited Positions, Funding - current & pending). We should also document this process in our documentation and what is written to ORCID.

Related: #28 FAQ

**Comment by DanCoughlin** [comment]
Potential Integration for ORCID fields from MDDB
Education & Qualifications
Employment
Works (Publications) (already in another ticket, separate)
Invited Positions
Membership/Services
Funding – note gonna have that one for current and pending

**Comment by ajkiessl** [comment]
#81

**Comment by EricDurante** [comment]
@ajkiessl I tried this out in production. I works like a champ! Nice job!
