### ISSUE TITLE
Email Text for OA Policy Reminder

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#76]
Dear Dan Coughlin,
 
Penn State Policy AC02: Open Access to Scholarly Articles, requires university researchers to provide the accepted manuscript version of their scholarly articles to the University Libraries to be made available to the public free of charge. Researchers who cannot or do not wish to make a particular article freely available can obtain a waiver. The policy went into effect on January 1, 2020 after endorsement by Faculty Senate and approval by the President’s Council and [does not apply to some articles](https://psu.libanswers.com/faq/279964) with publishing agreements signed before that date.

We have identified one or more publications published since July 1, 2020 for which you are listed as an author. We have not found an open access version of these publications. For items on the list that are [scholarly articles](https://psu.libanswers.com/faq/279967), please visit the links in the list below and follow the instructions to provide your [accepted manuscript](https://psu.libanswers.com/faq/279953), add a link to an open access version, or obtain a waiver of the policy. The links below will not work for other people.

New publications awaiting action:
- [Dan's Test Publication](this should be the same)

For more information on the policy, please visit the [open access policy website](https://openaccess.psu.edu/), including its FAQ section. Here are some [FAQs](https://openaccess.psu.edu/faq/) that may be especially helpful:

- [How can I check the terms of my publishing agreement regarding deposit of my scholarly article in ScholarSphere?](https://psu.libanswers.com/faq/279046)
- [Does public access to an article via a federal funder repository satisfy the Penn State open access policy?](https://psu.libanswers.com/faq/339761)
- [My article is already open access. Why did I get an email?](https://psu.libanswers.com/faq/339763)
- [I'm not the corresponding author on this article. Why did I get an email?](https://psu.libanswers.com/faq/339765)
- [Why should I make my work open access?](https://psu.libanswers.com/faq/332993)

Please don’t hesitate to follow up with us if you have any questions.

Sincerely,
The Office of Scholarly Communications and Copyright
Penn State University Libraries

**Comment by anaelizabethenriquez** [comment]
Revised text for July 2022:

Dear [First Last],

We're contacting you from the Penn State University Libraries about the following publication(s), for which you are listed as an author:

New publications awaiting action:
- [title]

Previous publications awaiting action:
- [title]

Pursuant to [Penn State's open access policy](https://openaccess.psu.edu/), we would like to assist you in making the [accepted manuscript version](https://psu.libanswers.com/faq/279953) of these publication(s) available to the public free of charge. Please click the link(s) above and follow the instructions to take one of the following actions:

- Submit a URL (Use this option if an open access version of your publication is already available anywhere on the public web.)
- Upload to ScholarSphere (If there isn't already an open access version of your work available on the web, please consider uploading the accepted manuscript version to ScholarSphere, an institutional repository maintained by the Libraries. Refer to [this FAQ to check the terms of your publishing agreement](https://psu.libanswers.com/faq/279046).)
- Get a Waiver (Use this option if you'd like to waive Penn State's policy for the publication in question, and we will not contact you about the publication again.)

The publication links will only work for you and designated proxies. If you would like to authorize someone else to take these actions on your behalf, please [designate them as your proxy](https://openaccess.psu.edu/proxies-in-the-researcher-metadata-database/).

If you would like assistance or have any questions, please reply to this email. If you have accepted manuscripts you would like us to deposit on your behalf, please attach them to a reply email. We will follow the policies of the journal(s) in question when depositing them to ScholarSphere.

You may also wish to review one of the following frequently asked questions:

- [My article is already open access. Why did I get an email?](https://psu.libanswers.com/faq/339763)
- [I'm not the corresponding author on this article. Why did I get an email?](https://psu.libanswers.com/faq/339765)
- [Does public access to an article via a federal funder repository satisfy the Penn State open access policy?](https://psu.libanswers.com/faq/339761)
- [Why should I make my work open access?](https://psu.libanswers.com/faq/332993)

Sincerely, 
The Office of Scholarly Communications and Copyright 
Penn State University Libraries
